# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Innocode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/Inno-ki/innocode"
  version "1.0.232"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.232/innocode-darwin-x64.zip"
      sha256 "24e7471a3c2339a4b33d8e04b297553035775eb77a5fcc4667081b98b5fd7428"

      def install
        bin.install "innocode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.232/innocode-darwin-arm64.zip"
      sha256 "71ab7a8f19029f6c565a2d69029388ddcd7d79dcf9ac674614fef05b0a0171c7"

      def install
        bin.install "innocode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.232/innocode-linux-x64.tar.gz"
      sha256 "d60219bb2dfa753f5f608f418825e3b87ef3c548393b0a39bc132bb2630bdf33"
      def install
        bin.install "innocode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.232/innocode-linux-arm64.tar.gz"
      sha256 "778463ee2644082dca8747c4b54f39c913e5d32742b5ee058d0e99bec03a2f03"
      def install
        bin.install "innocode"
      end
    end
  end
end

