# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Innocode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/Inno-ki/innocode"
  version "1.0.235"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.235/innocode-darwin-x64.zip"
      sha256 "591cb283b92618b91644df3ef7dcb577f1a046d9d2bcdbc14913bc8ed3983efd"

      def install
        bin.install "innocode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.235/innocode-darwin-arm64.zip"
      sha256 "9c5bae662250b1df68be734196e906bfedccede91f9c565ceea23475e484a96e"

      def install
        bin.install "innocode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.235/innocode-linux-x64.tar.gz"
      sha256 "a74212a533e70fc67f44e60ce0a79fa6a92962781dbafa7870c0f866ec4c221f"
      def install
        bin.install "innocode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.235/innocode-linux-arm64.tar.gz"
      sha256 "5d41384161b2c8e095660a06e51beb847eb2dc3c5b03157fa282fe3d35da5263"
      def install
        bin.install "innocode"
      end
    end
  end
end

