# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Innocode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/Inno-ki/innocode"
  version "1.0.237"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.237/innocode-darwin-x64.zip"
      sha256 "194782e8d4a87d4674e71ac2d3861dde98bdfe341bfadc081d707f42a210d451"

      def install
        bin.install "innocode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.237/innocode-darwin-arm64.zip"
      sha256 "a66e093716a57793432993a22855b7460e121268e7c40fa0d1406b93b1542888"

      def install
        bin.install "innocode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.237/innocode-linux-x64.tar.gz"
      sha256 "cd278120c37815b87fffa4510fd69dca7726b6883713475a6f1035fc5efaea9e"
      def install
        bin.install "innocode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Inno-ki/innocode/releases/download/v1.0.237/innocode-linux-arm64.tar.gz"
      sha256 "29d2c935aec51aca50d46e1a28befb73b307cdf596b08462229e11ba960c63e8"
      def install
        bin.install "innocode"
      end
    end
  end
end

